{{- if .Values.metrics.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kafka.fullname" . }}-exporter
  labels: {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  annotations: {{ include "kafka.tplValue" ( dict "value" .Values.metrics.kafka.annotations "context" $) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "kafka.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  template:
    metadata:
      labels: {{- include "kafka.labels" . | nindent 8 }}
        app.kubernetes.io/component: metrics
      annotations: {{ include "kafka.tplValue" ( dict "value" .Values.metrics.kafka.podAnnotations "context" $) | nindent 8 }}
    spec:
{{- include "kafka.imagePullSecrets" . | indent 6 }}
      containers:
        - image: {{ template  "kafka.metrics.kafka.image" . }}
          name: kafka-exporter
          args:
            - --kafka.server={{ template "kafka.fullname" . }}:{{ .Values.service.port }}
            - --web.listen-address=:{{ .Values.metrics.kafka.port }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.kafka.port }}
          {{- if .Values.metrics.kafka.resources }}
          resources: {{ toYaml .Values.metrics.kafka.resources | nindent 12 }}
          {{- end }}
{{- end }}
