apiVersion: v1
name: metallb
description: The Metal LB for Kubernetes
appVersion: 0.9.3
keywords:
  - "load-balancer"
  - "balancer"
  - "lb"
  - "bgp"
  - "arp"
  - "vrrp"
  - "vip"
home: https://metallb.universe.tf
icon: https://metallb.universe.tf/images/logo.png
sources:
  - https://github.com/metallb/metallb
  - https://github.com/bitnami/bitnami-docker-metallb
version: 0.1.11
maintainers:
  - name: cellebyte
    email: cellebyte@gmail.com
  - name: Bitnami
    email: containers@bitnami.com
